GET /oauth2/v3/userinfo
Host: www.googleapis.com
Authorization: Bearer ya29.a0Ad52N3-gN7Blfy5rFIxi7fiq5NyxkQe7Li-iEk5Yq-iBQdShU4bUcSl3VOE_QyXlfcBjxyUeUCAc55jM4skbn-rWR1TmSu7IVvWW0VgVNNf84dU76sNQ4dqe0puaIWZCk1WdXC3z4hZjoPaiYK1ThHE0uYLMW49z__AaCgYKAfgSARMSFQHGX2MidHTFFVchn6dGmqr8Ae3Ysg0170